
on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Add Conda
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install pip libraries
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest-cov
        pip install coverage
    - name: Install dependencies
      run: |
        conda env update --file requirements.txt --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # la build es para si hi ha cap problema
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero tractara tots el errors com avisos, lenght=127 es el tamany que te l'editor
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test
      run: |
        coverage run -m pytest .
        coverage report
