name: python app
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: analysis
      run: |
        pylint transform.py
        pylint main.py
    - name: test
      run: |
        echo "Run the tests:"
        python test.py
